### ISSUE TITLE
Launching with KCauldron or Thermos crashes the server

### ISSUE THREAD

**Issue by silent-mobious** [Ermans/BottledAnimals#2]
Launching with no other mods on a server using Thermos or KCauldron produces this crash:

[Server thread/ERROR] [FML/]: Caught exception from BottledAnimals
java.lang.NoSuchFieldError: sideAndFacingToSpriteOffset

Does this only support forge in single player?
http://pastebin.com/pFmTiGxt - kcauldron complete log

**Comment by ErmansMC** [comment]
I forgot to test on a dedicated server. I'll release the fix in few hours

**Comment by ErmansMC** [comment]
It is not releated to those mods, it's because is on a dedicated server

**Comment by ErmansMC** [comment]
Fixed with the 1.1.2 version ( [Download here](http://minecraft.curseforge.com/projects/bottled-animals/files) )
Thanks for catching it. Please keep reporting bugs ;)

**Comment by silent-mobious** [comment]
Confirmed it's working now, thanks a lot!!
